// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDent.Services.Database;

#nullable disable

namespace MyDent.Services.Migrations
{
    [DbContext(typeof(MyDentDbContext))]
    [Migration("20260826133737_RefreshSeedDataAndTimezoneFix")]
    partial class RefreshSeedDataAndTimezoneFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyDent.Services.Database.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DentalServiceId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Reminder24hSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Reminder2hSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("DentalServiceId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 1,
                            DoctorId = 1,
                            DurationMinutes = 30,
                            PatientId = 13,
                            Price = 40.00m,
                            ScheduledAt = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 9,
                            DoctorId = 5,
                            DurationMinutes = 45,
                            PatientId = 13,
                            Price = 150.00m,
                            ScheduledAt = new DateTime(2026, 8, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 5,
                            DoctorId = 3,
                            DurationMinutes = 60,
                            PatientId = 14,
                            Price = 1200.00m,
                            ScheduledAt = new DateTime(2026, 8, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 4,
                            CancellationReason = "Pacijent otkazao termin zbog bolesti.",
                            CancelledAt = new DateTime(2026, 8, 19, 20, 0, 0, 0, DateTimeKind.Utc),
                            CancelledByUserId = 14,
                            CreatedAt = new DateTime(2026, 8, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 7,
                            DoctorId = 4,
                            DurationMinutes = 60,
                            PatientId = 14,
                            Price = 350.00m,
                            ScheduledAt = new DateTime(2026, 8, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 8, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 2,
                            DoctorId = 1,
                            DurationMinutes = 45,
                            PatientId = 15,
                            Price = 80.00m,
                            ScheduledAt = new DateTime(2026, 8, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 6,
                            CancellationReason = "Ordinacija otkazala termin – doktor odsutan zbog bolesti.",
                            CancelledAt = new DateTime(2026, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            CancelledByUserId = 12,
                            CreatedAt = new DateTime(2026, 8, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 3,
                            DoctorId = 2,
                            DurationMinutes = 30,
                            PatientId = 15,
                            Price = 60.00m,
                            ScheduledAt = new DateTime(2026, 8, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 8, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 6,
                            DoctorId = 3,
                            DurationMinutes = 20,
                            PatientId = 16,
                            Price = 50.00m,
                            ScheduledAt = new DateTime(2026, 8, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 8, 19, 8, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 8,
                            DoctorId = 4,
                            DurationMinutes = 90,
                            PatientId = 16,
                            Price = 700.00m,
                            ScheduledAt = new DateTime(2026, 8, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 8, 24, 8, 30, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 10,
                            DoctorId = 5,
                            DurationMinutes = 30,
                            PatientId = 17,
                            Price = 70.00m,
                            ScheduledAt = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 8, 26, 7, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 1,
                            DoctorId = 1,
                            DurationMinutes = 30,
                            PatientId = 17,
                            Price = 40.00m,
                            ScheduledAt = new DateTime(2026, 8, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 8, 26, 7, 30, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 7,
                            DoctorId = 4,
                            DurationMinutes = 60,
                            PatientId = 18,
                            Price = 350.00m,
                            ScheduledAt = new DateTime(2026, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 8, 25, 11, 30, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 5,
                            DoctorId = 3,
                            DurationMinutes = 60,
                            PatientId = 18,
                            Price = 1200.00m,
                            ScheduledAt = new DateTime(2026, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 8, 25, 12, 30, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 9,
                            DoctorId = 5,
                            DurationMinutes = 45,
                            PatientId = 13,
                            Price = 150.00m,
                            ScheduledAt = new DateTime(2026, 9, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 8, 26, 8, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 2,
                            DoctorId = 1,
                            DurationMinutes = 45,
                            PatientId = 14,
                            Price = 80.00m,
                            ScheduledAt = new DateTime(2026, 9, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 8, 24, 11, 30, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 6,
                            DoctorId = 3,
                            DurationMinutes = 20,
                            PatientId = 15,
                            Price = 50.00m,
                            ScheduledAt = new DateTime(2026, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CancellationReason = "Promjena planova, pacijent otkazao termin.",
                            CancelledAt = new DateTime(2026, 8, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            CancelledByUserId = 16,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 9,
                            DoctorId = 5,
                            DurationMinutes = 45,
                            PatientId = 16,
                            Price = 150.00m,
                            ScheduledAt = new DateTime(2026, 9, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 8, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 1,
                            DoctorId = 1,
                            DurationMinutes = 30,
                            PatientId = 17,
                            Price = 40.00m,
                            ScheduledAt = new DateTime(2026, 9, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 8, 26, 7, 45, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 10,
                            DoctorId = 5,
                            DurationMinutes = 30,
                            PatientId = 18,
                            Price = 70.00m,
                            ScheduledAt = new DateTime(2026, 9, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 8, 19, 8, 30, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 3,
                            DoctorId = 2,
                            DurationMinutes = 30,
                            PatientId = 13,
                            Price = 60.00m,
                            ScheduledAt = new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.AppointmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("AppointmentStatusHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ChangedAt = new DateTime(2026, 8, 20, 9, 35, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            ChangedAt = new DateTime(2026, 8, 22, 10, 50, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            ChangedAt = new DateTime(2026, 8, 25, 11, 5, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            ChangedAt = new DateTime(2026, 8, 19, 20, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 14,
                            FromStatus = 0,
                            Reason = "Pacijent otkazao termin zbog bolesti.",
                            ToStatus = 2
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 5,
                            ChangedAt = new DateTime(2026, 8, 21, 8, 50, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 6,
                            ChangedAt = new DateTime(2026, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 0,
                            Reason = "Ordinacija otkazala termin – doktor odsutan zbog bolesti.",
                            ToStatus = 2
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 7,
                            ChangedAt = new DateTime(2026, 8, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 0,
                            ToStatus = 1
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 8,
                            ChangedAt = new DateTime(2026, 8, 24, 9, 35, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 9,
                            ChangedAt = new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 0,
                            ToStatus = 1
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 12,
                            ChangedAt = new DateTime(2026, 8, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 0,
                            ToStatus = 1
                        },
                        new
                        {
                            Id = 11,
                            AppointmentId = 13,
                            ChangedAt = new DateTime(2026, 8, 25, 13, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 0,
                            ToStatus = 1
                        },
                        new
                        {
                            Id = 12,
                            AppointmentId = 15,
                            ChangedAt = new DateTime(2026, 8, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 0,
                            ToStatus = 1
                        },
                        new
                        {
                            Id = 13,
                            AppointmentId = 16,
                            ChangedAt = new DateTime(2026, 8, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 16,
                            FromStatus = 1,
                            Reason = "Promjena planova, pacijent otkazao termin.",
                            ToStatus = 2
                        },
                        new
                        {
                            Id = 14,
                            AppointmentId = 17,
                            ChangedAt = new DateTime(2026, 8, 26, 14, 10, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 0,
                            ToStatus = 1
                        },
                        new
                        {
                            Id = 15,
                            AppointmentId = 19,
                            ChangedAt = new DateTime(2026, 8, 24, 9, 35, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 12,
                            FromStatus = 1,
                            ToStatus = 3
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MyDent.Services.Database.DentalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("ImageAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageAssetId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("DentalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Osnovni stomatološki pregled sa savjetovanjem.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Pregled i konsultacije",
                            Price = 40.00m,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sanacija karijesa kompozitnim ispunom.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Plombiranje zuba",
                            Price = 80.00m,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ekstrakcija zuba u lokalnoj anesteziji.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Vađenje zuba",
                            Price = 60.00m,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hirurška ugradnja zubnog implantata.",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Ugradnja implantata",
                            Price = 900.00m,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ugradnja fiksnog ortodontskog aparatića.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Postavljanje aparatića",
                            Price = 1200.00m,
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Redovna kontrola i podešavanje aparatića.",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Kontrola aparatića",
                            Price = 50.00m,
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Izrada i postavljanje zubne krunice.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Izrada krunice",
                            Price = 350.00m,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protetski most za nadomjeranje više zuba.",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Izrada mosta",
                            Price = 700.00m,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profesionalno bijeljenje zuba u ordinaciji.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Bijeljenje zuba",
                            Price = 150.00m,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uklanjanje zubnog kamenca i poliranje.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Čišćenje kamenca",
                            Price = 70.00m,
                            ServiceCategoryId = 5
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PhotoAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhotoAssetId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Specijalista opće stomatologije sa 12 godina iskustva.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Amina",
                            IsActive = true,
                            LastName = "Hodžić"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Specijalista oralne hirurgije, fokus na implantologiju.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Emir",
                            IsActive = true,
                            LastName = "Karić"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Ortodontkinja, radi sa djecom i odraslima.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Selma",
                            IsActive = true,
                            LastName = "Begić"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Specijalista protetike, izrada krunica i mostova.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Adnan",
                            IsActive = true,
                            LastName = "Musić"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Doktorica opće i estetske stomatologije.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Lejla",
                            IsActive = true,
                            LastName = "Softić"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorAbsence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAbsences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            EndDate = new DateOnly(2026, 9, 10),
                            Reason = "Godišnji odmor",
                            StartDate = new DateOnly(2026, 9, 1)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            EndDate = new DateOnly(2026, 7, 5),
                            Reason = "Stručno usavršavanje",
                            StartDate = new DateOnly(2026, 7, 1)
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("DoctorSpecialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 2,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 3,
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 4,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 5,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            DoctorId = 5,
                            ServiceCategoryId = 1
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorWorkingHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 3,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 5,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 2,
                            DoctorId = 3,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 4,
                            DoctorId = 3,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 1,
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 2,
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 3,
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 4,
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 3,
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 4,
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 5,
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 6,
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ImageAssetId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sa zadovoljstvom najavljujemo otvaranje naše nove, moderno opremljene ordinacije u centru grada. Dobrodošli!",
                            CreatedAt = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 12,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Nova ordinacija otvorena u centru grada"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Tokom mjeseca maja, svi novi pacijenti imaju pravo na besplatan prvi pregled i konsultaciju.",
                            CreatedAt = new DateTime(2026, 5, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 12,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 5, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Akcija: besplatan pregled za nove pacijente"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Obavještavamo pacijente da ordinacija za vrijeme predstojećih praznika radi po skraćenom radnom vremenu.",
                            CreatedAt = new DateTime(2026, 6, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 12,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 6, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Radno vrijeme tokom praznika"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Od sada možete zakazati svoj termin direktno putem mobilne aplikacije, bez potrebe za pozivom.",
                            CreatedAt = new DateTime(2026, 7, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 12,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Uvodimo online zakazivanje termina"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Termine sada možete platiti direktno u mobilnoj aplikaciji, sigurno i jednostavno, putem platne kartice.",
                            CreatedAt = new DateTime(2026, 8, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 12,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 8, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Plaćanje karticom sada dostupno u aplikaciji"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Priprema se javni seminar o pravilnoj njezi zubi za djecu — detalji uskoro.",
                            CreatedAt = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 12,
                            IsPublished = false,
                            PublishedAt = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Najava novog seminara o njezi zuba"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 8, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Vaš termin zakazan za 20.08.2026. u 09:00 je potvrđen.",
                            Title = "Termin potvrđen",
                            Type = 1,
                            UserId = 13
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 6, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Uplata od 40.00 KM za termin 20.08.2026. je uspješno izvršena.",
                            Title = "Plaćanje uspješno",
                            Type = 5,
                            UserId = 13
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2026, 8, 23, 12, 1, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Izvršena je refundacija u iznosu od 150.00 KM za termin 22.08.2026.",
                            Title = "Refundacija izvršena",
                            Type = 6,
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 13,
                            CreatedAt = new DateTime(2026, 8, 25, 13, 6, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Vaš termin zakazan za 02.09.2026. u 09:00 je potvrđen.",
                            Title = "Termin potvrđen",
                            Type = 1,
                            UserId = 13
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2026, 8, 19, 20, 5, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Vaš termin zakazan za 20.08.2026. u 08:00 je otkazan. Razlog: Pacijent otkazao termin zbog bolesti.",
                            Title = "Termin otkazan",
                            Type = 2,
                            UserId = 14
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Vaš termin zakazan za 25.08.2026. u 10:00 je potvrđen.",
                            Title = "Termin potvrđen",
                            Type = 1,
                            UserId = 14
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 8, 26, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Preporučujemo da zakažete termin za \"Ortodoncija\" — prošlo je 2 mjeseca od zadnje posjete.",
                            ServiceCategoryId = 3,
                            Title = "Vrijeme je za kontrolu",
                            Type = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 6,
                            CreatedAt = new DateTime(2026, 8, 20, 15, 5, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Vaš termin zakazan za 21.08.2026. u 09:00 je otkazan. Razlog: Ordinacija otkazala termin – doktor odsutan zbog bolesti.",
                            Title = "Termin otkazan",
                            Type = 2,
                            UserId = 15
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2026, 8, 21, 8, 6, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Uplata od 80.00 KM za termin 21.08.2026. je uspješno izvršena.",
                            Title = "Plaćanje uspješno",
                            Type = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 7,
                            CreatedAt = new DateTime(2026, 8, 26, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Podsjetnik: termin za \"Kontrola aparatića\" zakazan je za 27.08.2026. u 10:00.",
                            Title = "Podsjetnik za termin",
                            Type = 3,
                            UserId = 16
                        },
                        new
                        {
                            Id = 11,
                            AppointmentId = 8,
                            CreatedAt = new DateTime(2026, 8, 24, 8, 6, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Uplata od 700.00 KM za termin 24.08.2026. je uspješno izvršena.",
                            Title = "Plaćanje uspješno",
                            Type = 5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 12,
                            AppointmentId = 16,
                            CreatedAt = new DateTime(2026, 8, 26, 9, 5, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Vaš termin zakazan za 04.09.2026. u 09:00 je otkazan. Razlog: Promjena planova, pacijent otkazao termin.",
                            Title = "Termin otkazan",
                            Type = 2,
                            UserId = 16
                        },
                        new
                        {
                            Id = 13,
                            AppointmentId = 9,
                            CreatedAt = new DateTime(2026, 8, 24, 8, 35, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Plaćanje za termin zakazan 28.08.2026. još nije izvršeno. Možete platiti karticom u aplikaciji ili na recepciji.",
                            Title = "Plaćanje na čekanju",
                            Type = 0,
                            UserId = 17
                        },
                        new
                        {
                            Id = 14,
                            AppointmentId = 12,
                            CreatedAt = new DateTime(2026, 8, 25, 12, 5, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Plaćanje karticom za termin 03.09.2026. nije uspjelo. Molimo pokušajte ponovo ili platite na recepciji.",
                            Title = "Plaćanje neuspješno",
                            Type = 0,
                            UserId = 18
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("MyDent.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("RefundedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 40.00m,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 20, 9, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0001",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 150.00m,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2026, 8, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 22, 10, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0002",
                            RefundedAmount = 150.00m,
                            RefundedAt = new DateTime(2026, 8, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1200.00m,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2026, 8, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 25, 10, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0003",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 80.00m,
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2026, 8, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 21, 8, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0004",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 50.00m,
                            AppointmentId = 7,
                            CreatedAt = new DateTime(2026, 8, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 23, 10, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0005",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 700.00m,
                            AppointmentId = 8,
                            CreatedAt = new DateTime(2026, 8, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 24, 8, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0006",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 70.00m,
                            AppointmentId = 9,
                            CreatedAt = new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0007",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1200.00m,
                            AppointmentId = 12,
                            CreatedAt = new DateTime(2026, 8, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0008",
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 150.00m,
                            AppointmentId = 13,
                            CreatedAt = new DateTime(2026, 8, 25, 13, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 25, 13, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0009",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 40.00m,
                            AppointmentId = 17,
                            CreatedAt = new DateTime(2026, 8, 26, 14, 5, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 26, 14, 10, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0010",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 60.00m,
                            AppointmentId = 19,
                            CreatedAt = new DateTime(2026, 8, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 8, 24, 9, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0011",
                            Status = 1
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MyDent.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Comment = "Odličan pregled, sve pohvale za osoblje.",
                            CreatedAt = new DateTime(2026, 8, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            Comment = "Nisam bila zadovoljna rezultatom, ali su brzo riješili refundaciju.",
                            CreatedAt = new DateTime(2026, 8, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Rating = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            Comment = "Doktorica Selma je izuzetna, aparatić savršeno stoji.",
                            CreatedAt = new DateTime(2026, 8, 25, 13, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 5,
                            Comment = "Sve je prošlo dobro, malo duže čekanje u čekaonici.",
                            CreatedAt = new DateTime(2026, 8, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = false,
                            Rating = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 8,
                            Comment = "Profesionalno urađen most, preporučujem.",
                            CreatedAt = new DateTime(2026, 8, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clinic administrator/staff role with full permissions",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default patient role",
                            IsActive = true,
                            Name = "Patient"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RecommendedRecallMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Redovni pregledi, plombiranje i osnovna njega zuba.",
                            IsActive = true,
                            Name = "Opća stomatologija",
                            RecommendedRecallMonths = 6
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vađenje zuba i hirurški zahvati u usnoj šupljini.",
                            IsActive = true,
                            Name = "Oralna hirurgija"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Aparatići i korekcija položaja zuba.",
                            IsActive = true,
                            Name = "Ortodoncija",
                            RecommendedRecallMonths = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Krunice, mostovi i nadomjesci zuba.",
                            IsActive = true,
                            Name = "Protetika",
                            RecommendedRecallMonths = 12
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bijeljenje zuba i estetski tretmani.",
                            IsActive = true,
                            Name = "Estetska stomatologija"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProfileImageAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("PushNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileImageAssetId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "desktop.test@mydent.example",
                            EmailNotificationsEnabled = true,
                            FirstName = "Desktop",
                            IsActive = true,
                            LastName = "Test",
                            PasswordHash = "XEl2qoKu2YArgsq1Y3VhlyjqjiM=",
                            PasswordSalt = "roKn7IGTdP3yztR2+qc+7Q==",
                            PushNotificationsEnabled = true,
                            Username = "desktop"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mobile.test@mydent.example",
                            EmailNotificationsEnabled = true,
                            FirstName = "Mobile",
                            IsActive = true,
                            LastName = "Test",
                            PasswordHash = "omyGZFUqPKsvhuX2Id1vnNGw+pE=",
                            PasswordSalt = "ytRbBjA/SsKMyuSRMtS95A==",
                            PushNotificationsEnabled = true,
                            Username = "mobile"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amar.suljic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Amar",
                            IsActive = true,
                            LastName = "Suljić",
                            PasswordHash = "97CVsdb/RriIbmq6bSLnkSnk2iY=",
                            PasswordSalt = "4Ia0/2SixvL552HJpHjlgg==",
                            PhoneNumber = "062111222",
                            PushNotificationsEnabled = true,
                            Username = "asuljic"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ilma.becirovic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Ilma",
                            IsActive = true,
                            LastName = "Bećirović",
                            PasswordHash = "cf3yE2GIp3+cXoY7rxCtZ0wQ3T0=",
                            PasswordSalt = "GUOSx+2UVWR8r6putOWSFQ==",
                            PhoneNumber = "062222333",
                            PushNotificationsEnabled = true,
                            Username = "ibecirovic"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tarik.osmic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Tarik",
                            IsActive = true,
                            LastName = "Osmić",
                            PasswordHash = "/ueyOZg03JjVC4PhcfggPVwSopo=",
                            PasswordSalt = "lnUGNEkE0VBne8/BxJW3Dg==",
                            PhoneNumber = "062333444",
                            PushNotificationsEnabled = true,
                            Username = "tosmic"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "merima.halilovic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Merima",
                            IsActive = true,
                            LastName = "Halilović",
                            PasswordHash = "XGjZ4G5uhNA9ysjR7puJ4sCO6qc=",
                            PasswordSalt = "4gJcUoPg8r1Cmhs+S0OzUQ==",
                            PhoneNumber = "062444555",
                            PushNotificationsEnabled = true,
                            Username = "mhalilovic"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "denis.jasarevic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Denis",
                            IsActive = true,
                            LastName = "Jašarević",
                            PasswordHash = "U6zyYv8whKf1pxsYgNBFwim3Tj0=",
                            PasswordSalt = "KUSI2gGKGZ6GIf3b+heKMQ==",
                            PhoneNumber = "062555666",
                            PushNotificationsEnabled = true,
                            Username = "djasarevic"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            DateAssigned = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            DateAssigned = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            DateAssigned = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            DateAssigned = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            DateAssigned = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 18
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Appointment", b =>
                {
                    b.HasOne("MyDent.Services.Database.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyDent.Services.Database.DentalService", "DentalService")
                        .WithMany("Appointments")
                        .HasForeignKey("DentalServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("DentalService");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MyDent.Services.Database.AppointmentStatusHistory", b =>
                {
                    b.HasOne("MyDent.Services.Database.Appointment", "Appointment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("MyDent.Services.Database.DentalService", b =>
                {
                    b.HasOne("MyDent.Services.Database.Asset", "Image")
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyDent.Services.Database.ServiceCategory", "ServiceCategory")
                        .WithMany("DentalServices")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("MyDent.Services.Database.Doctor", b =>
                {
                    b.HasOne("MyDent.Services.Database.Asset", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorAbsence", b =>
                {
                    b.HasOne("MyDent.Services.Database.Doctor", "Doctor")
                        .WithMany("Absences")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorSpecialty", b =>
                {
                    b.HasOne("MyDent.Services.Database.Doctor", "Doctor")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.ServiceCategory", "ServiceCategory")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorWorkingHours", b =>
                {
                    b.HasOne("MyDent.Services.Database.Doctor", "Doctor")
                        .WithMany("WorkingHours")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MyDent.Services.Database.News", b =>
                {
                    b.HasOne("MyDent.Services.Database.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.Asset", "Image")
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyDent.Services.Database.Notification", b =>
                {
                    b.HasOne("MyDent.Services.Database.Appointment", "Appointment")
                        .WithMany("Notifications")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyDent.Services.Database.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyDent.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ServiceCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDent.Services.Database.PasswordResetToken", b =>
                {
                    b.HasOne("MyDent.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDent.Services.Database.Payment", b =>
                {
                    b.HasOne("MyDent.Services.Database.Appointment", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("MyDent.Services.Database.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MyDent.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("MyDent.Services.Database.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDent.Services.Database.Review", b =>
                {
                    b.HasOne("MyDent.Services.Database.Appointment", "Appointment")
                        .WithOne("Review")
                        .HasForeignKey("MyDent.Services.Database.Review", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MyDent.Services.Database.User", b =>
                {
                    b.HasOne("MyDent.Services.Database.Asset", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImageAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("MyDent.Services.Database.UserRole", b =>
                {
                    b.HasOne("MyDent.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDent.Services.Database.Appointment", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Payment");

                    b.Navigation("Review");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("MyDent.Services.Database.DentalService", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MyDent.Services.Database.Doctor", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Appointments");

                    b.Navigation("DoctorSpecialties");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("MyDent.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MyDent.Services.Database.ServiceCategory", b =>
                {
                    b.Navigation("DentalServices");

                    b.Navigation("DoctorSpecialties");
                });

            modelBuilder.Entity("MyDent.Services.Database.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
