// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDent.Services.Database;

#nullable disable

namespace MyDent.Services.Migrations
{
    [DbContext(typeof(MyDentDbContext))]
    [Migration("20260820084919_AddPatientHealthRecordFields")]
    partial class AddPatientHealthRecordFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyDent.Services.Database.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DentalServiceId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Reminder24hSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Reminder2hSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("DentalServiceId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 1,
                            DoctorId = 1,
                            DurationMinutes = 30,
                            PatientId = 4,
                            Price = 40.00m,
                            ScheduledAt = new DateTime(2026, 1, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 1,
                            DoctorId = 1,
                            DurationMinutes = 30,
                            PatientId = 5,
                            Price = 40.00m,
                            ScheduledAt = new DateTime(2026, 7, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 7,
                            DoctorId = 4,
                            DurationMinutes = 60,
                            PatientId = 5,
                            Price = 350.00m,
                            ScheduledAt = new DateTime(2026, 6, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 9,
                            DoctorId = 5,
                            DurationMinutes = 45,
                            PatientId = 7,
                            Price = 150.00m,
                            ScheduledAt = new DateTime(2026, 7, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 10,
                            DoctorId = 5,
                            DurationMinutes = 30,
                            PatientId = 7,
                            Price = 70.00m,
                            ScheduledAt = new DateTime(2026, 7, 12, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 5,
                            DoctorId = 3,
                            DurationMinutes = 60,
                            PatientId = 8,
                            Price = 1200.00m,
                            ScheduledAt = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 3,
                            DoctorId = 2,
                            DurationMinutes = 30,
                            PatientId = 9,
                            Price = 60.00m,
                            ScheduledAt = new DateTime(2026, 3, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 2,
                            DoctorId = 1,
                            DurationMinutes = 45,
                            PatientId = 9,
                            Price = 80.00m,
                            ScheduledAt = new DateTime(2026, 4, 18, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 9,
                            CancellationReason = "Pacijent otkazao termin.",
                            CancelledAt = new DateTime(2026, 3, 30, 18, 0, 0, 0, DateTimeKind.Utc),
                            CancelledByUserId = 10,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 3,
                            DoctorId = 2,
                            DurationMinutes = 30,
                            PatientId = 10,
                            Price = 60.00m,
                            ScheduledAt = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 8,
                            DoctorId = 4,
                            DurationMinutes = 90,
                            PatientId = 4,
                            Price = 700.00m,
                            ScheduledAt = new DateTime(2026, 2, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DentalServiceId = 1,
                            DoctorId = 1,
                            DurationMinutes = 30,
                            PatientId = 11,
                            Price = 40.00m,
                            ScheduledAt = new DateTime(2026, 7, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.AppointmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("AppointmentStatusHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ChangedAt = new DateTime(2026, 1, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            ChangedAt = new DateTime(2026, 7, 10, 9, 30, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            ChangedAt = new DateTime(2026, 6, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            ChangedAt = new DateTime(2026, 7, 5, 13, 45, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 5,
                            ChangedAt = new DateTime(2026, 7, 12, 13, 30, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 6,
                            ChangedAt = new DateTime(2026, 5, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 7,
                            ChangedAt = new DateTime(2026, 3, 22, 14, 30, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 8,
                            ChangedAt = new DateTime(2026, 4, 18, 10, 15, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 9,
                            ChangedAt = new DateTime(2026, 3, 30, 18, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 10,
                            FromStatus = 0,
                            Reason = "Pacijent otkazao termin.",
                            ToStatus = 2
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 10,
                            ChangedAt = new DateTime(2026, 2, 14, 16, 30, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        },
                        new
                        {
                            Id = 11,
                            AppointmentId = 11,
                            ChangedAt = new DateTime(2026, 7, 25, 11, 30, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            FromStatus = 1,
                            ToStatus = 3
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MyDent.Services.Database.DentalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("ImageAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageAssetId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("DentalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Osnovni stomatološki pregled sa savjetovanjem.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Pregled i konsultacije",
                            Price = 40.00m,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sanacija karijesa kompozitnim ispunom.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Plombiranje zuba",
                            Price = 80.00m,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ekstrakcija zuba u lokalnoj anesteziji.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Vađenje zuba",
                            Price = 60.00m,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hirurška ugradnja zubnog implantata.",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Ugradnja implantata",
                            Price = 900.00m,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ugradnja fiksnog ortodontskog aparatića.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Postavljanje aparatića",
                            Price = 1200.00m,
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Redovna kontrola i podešavanje aparatića.",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Kontrola aparatića",
                            Price = 50.00m,
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Izrada i postavljanje zubne krunice.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Izrada krunice",
                            Price = 350.00m,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protetski most za nadomjeranje više zuba.",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Izrada mosta",
                            Price = 700.00m,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profesionalno bijeljenje zuba u ordinaciji.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Bijeljenje zuba",
                            Price = 150.00m,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uklanjanje zubnog kamenca i poliranje.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Čišćenje kamenca",
                            Price = 70.00m,
                            ServiceCategoryId = 5
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PhotoAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhotoAssetId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Specijalista opće stomatologije sa 12 godina iskustva.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Amina",
                            IsActive = true,
                            LastName = "Hodžić"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Specijalista oralne hirurgije, fokus na implantologiju.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Emir",
                            IsActive = true,
                            LastName = "Karić"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Ortodontkinja, radi sa djecom i odraslima.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Selma",
                            IsActive = true,
                            LastName = "Begić"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Specijalista protetike, izrada krunica i mostova.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Adnan",
                            IsActive = true,
                            LastName = "Musić"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Doktorica opće i estetske stomatologije.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Lejla",
                            IsActive = true,
                            LastName = "Softić"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorAbsence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAbsences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            EndDate = new DateOnly(2026, 9, 10),
                            Reason = "Godišnji odmor",
                            StartDate = new DateOnly(2026, 9, 1)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            EndDate = new DateOnly(2026, 7, 5),
                            Reason = "Stručno usavršavanje",
                            StartDate = new DateOnly(2026, 7, 1)
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("DoctorSpecialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 2,
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 3,
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 4,
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 5,
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            DoctorId = 5,
                            ServiceCategoryId = 1
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorWorkingHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 3,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 5,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 2,
                            DoctorId = 3,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 4,
                            DoctorId = 3,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 1,
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 2,
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 3,
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 4,
                            DoctorId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 3,
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 4,
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 5,
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 6,
                            DoctorId = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ImageAssetId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sa zadovoljstvom najavljujemo otvaranje naše nove, moderno opremljene ordinacije u centru grada. Dobrodošli!",
                            CreatedAt = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Nova ordinacija otvorena u centru grada"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Tokom mjeseca maja, svi novi pacijenti imaju pravo na besplatan prvi pregled i konsultaciju.",
                            CreatedAt = new DateTime(2026, 5, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 5, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Akcija: besplatan pregled za nove pacijente"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Obavještavamo pacijente da ordinacija za vrijeme predstojećih praznika radi po skraćenom radnom vremenu.",
                            CreatedAt = new DateTime(2026, 6, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 6, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Radno vrijeme tokom praznika"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Od sada možete zakazati svoj termin direktno putem mobilne aplikacije, bez potrebe za pozivom.",
                            CreatedAt = new DateTime(2026, 7, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Uvodimo online zakazivanje termina"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Priprema se javni seminar o pravilnoj njezi zubi za djecu — detalji uskoro.",
                            CreatedAt = new DateTime(2026, 8, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 3,
                            IsPublished = false,
                            PublishedAt = new DateTime(2026, 8, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Najava novog seminara o njezi zuba"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Vaš termin zakazan za 20.01.2026. u 10:00 je potvrđen.",
                            Title = "Termin potvrđen",
                            Type = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Preporučujemo da zakažete termin za \"Opća stomatologija\" — prošlo je 6 mjeseci od zadnje posjete.",
                            ServiceCategoryId = 1,
                            Title = "Vrijeme je za kontrolu",
                            Type = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 9,
                            CreatedAt = new DateTime(2026, 3, 30, 18, 5, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Vaš termin zakazan za 01.04.2026. u 10:00 je otkazan. Razlog: Pacijent otkazao termin.",
                            Title = "Termin otkazan",
                            Type = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Preporučujemo da zakažete termin za \"Ortodoncija\" — prošlo je 2 mjeseca od zadnje posjete.",
                            ServiceCategoryId = 3,
                            Title = "Vrijeme je za kontrolu",
                            Type = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Message = "Vaš termin zakazan za 10.07.2026. u 09:00 je potvrđen.",
                            Title = "Termin potvrđen",
                            Type = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Vaš termin zakazan za 05.07.2026. u 13:00 je potvrđen.",
                            Title = "Termin potvrđen",
                            Type = 1,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("RefundedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 40.00m,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 1, 20, 10, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0001",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1200.00m,
                            AppointmentId = 6,
                            CreatedAt = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 5, 10, 10, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0002",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 350.00m,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 6, 15, 11, 5, 0, 0, DateTimeKind.Utc),
                            ProviderTransactionId = "pi_seed_0003",
                            Status = 1
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MyDent.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Comment = "Odličan pregled, doktorica je bila vrlo profesionalna.",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 4,
                            Comment = "Zadovoljan sam rezultatom bijeljenja.",
                            CreatedAt = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 5,
                            Comment = "Uredu, mogla je usluga biti malo brža.",
                            CreatedAt = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = false,
                            Rating = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 6,
                            Comment = "Vrlo zadovoljna, doktorica Selma je fantastična sa pacijentima.",
                            CreatedAt = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clinic administrator/staff role with full permissions",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default patient role",
                            IsActive = true,
                            Name = "Patient"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RecommendedRecallMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Redovni pregledi, plombiranje i osnovna njega zuba.",
                            IsActive = true,
                            Name = "Opća stomatologija",
                            RecommendedRecallMonths = 6
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vađenje zuba i hirurški zahvati u usnoj šupljini.",
                            IsActive = true,
                            Name = "Oralna hirurgija"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Aparatići i korekcija položaja zuba.",
                            IsActive = true,
                            Name = "Ortodoncija",
                            RecommendedRecallMonths = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Krunice, mostovi i nadomjesci zuba.",
                            IsActive = true,
                            Name = "Protetika",
                            RecommendedRecallMonths = 12
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bijeljenje zuba i estetski tretmani.",
                            IsActive = true,
                            Name = "Estetska stomatologija"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProfileImageAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("PushNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileImageAssetId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin1@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "5kRBQg4Ufcx4hAknG7P9zhfLPvY=",
                            PasswordSalt = "FmvmUwPsJyRRffhNRQvbrA==",
                            PushNotificationsEnabled = true,
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "GBoyh1WP+OMgGjqRj6vK6L1+oGc=",
                            PasswordSalt = "0AXpKx6xRp9xM42jCf/PiA==",
                            PushNotificationsEnabled = true,
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin3@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Carol",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "x6JHKCTQywdAzTcZxGWFvrKPORM=",
                            PasswordSalt = "IwhTfKQNgyqWfOlTqCDXrg==",
                            PushNotificationsEnabled = true,
                            Username = "admin3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient1@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Dave",
                            IsActive = true,
                            LastName = "Patient",
                            PasswordHash = "E0fA2/f9GZvIRRt/cgqQemG/Cog=",
                            PasswordSalt = "TiJxWTJcd7sBSiWNbhK9Vw==",
                            PushNotificationsEnabled = true,
                            Username = "patient1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient2@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Eve",
                            IsActive = true,
                            LastName = "Patient",
                            PasswordHash = "Ov4LxpWKXXV9dwMYvBgqODdzIt0=",
                            PasswordSalt = "KtWF6g7SemBqs4nVWV4Ziw==",
                            PushNotificationsEnabled = true,
                            Username = "patient2"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amila.hasic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Amila",
                            IsActive = true,
                            LastName = "Hasić",
                            PasswordHash = "QltLi5GKYeCHaOehVfriIIhPfG0=",
                            PasswordSalt = "HjfA2PFxZSH9zSYIKufiUA==",
                            PhoneNumber = "061111222",
                            PushNotificationsEnabled = true,
                            Username = "ahasic"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "faruk.delic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Faruk",
                            IsActive = true,
                            LastName = "Delić",
                            PasswordHash = "V21TmB3/VulNFWlmvlYckBYSSpQ=",
                            PasswordSalt = "WPc0zv025PwK+O/0+Pj3LA==",
                            PhoneNumber = "061222333",
                            PushNotificationsEnabled = true,
                            Username = "fdelic"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "selma.kovacevic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Selma",
                            IsActive = true,
                            LastName = "Kovačević",
                            PasswordHash = "uSUoCV2SnmYw7COgUfoADfl2CmQ=",
                            PasswordSalt = "EzJbcNnW0M0/H6fmm3r79A==",
                            PhoneNumber = "061333444",
                            PushNotificationsEnabled = true,
                            Username = "skovacevic"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nedim.zukic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Nedim",
                            IsActive = true,
                            LastName = "Zukić",
                            PasswordHash = "Sxcx82eS5eyS6RQdOSqrblwKi+c=",
                            PasswordSalt = "UzF2pmAXcvHgrmgwwXfhQQ==",
                            PhoneNumber = "061444555",
                            PushNotificationsEnabled = true,
                            Username = "nzukic"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emina.sabic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Emina",
                            IsActive = true,
                            LastName = "Šabić",
                            PasswordHash = "oFdWjtfrOcx4I1FtFkL5S14dtqY=",
                            PasswordSalt = "PJWyTaDYf+uNjdKNHciOuQ==",
                            PhoneNumber = "061555666",
                            PushNotificationsEnabled = true,
                            Username = "esabic"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "haris.kurtovic@gmail.com",
                            EmailNotificationsEnabled = true,
                            FirstName = "Haris",
                            IsActive = true,
                            LastName = "Kurtović",
                            PasswordHash = "wRuW4ybXsRCRf9NF+6EgFOUCEBc=",
                            PasswordSalt = "mILDpEhLR9HlSIOzqraY/A==",
                            PhoneNumber = "061666777",
                            PushNotificationsEnabled = true,
                            Username = "hkurtovic"
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 11
                        });
                });

            modelBuilder.Entity("MyDent.Services.Database.Appointment", b =>
                {
                    b.HasOne("MyDent.Services.Database.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyDent.Services.Database.DentalService", "DentalService")
                        .WithMany("Appointments")
                        .HasForeignKey("DentalServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("DentalService");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MyDent.Services.Database.AppointmentStatusHistory", b =>
                {
                    b.HasOne("MyDent.Services.Database.Appointment", "Appointment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("MyDent.Services.Database.DentalService", b =>
                {
                    b.HasOne("MyDent.Services.Database.Asset", "Image")
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyDent.Services.Database.ServiceCategory", "ServiceCategory")
                        .WithMany("DentalServices")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("MyDent.Services.Database.Doctor", b =>
                {
                    b.HasOne("MyDent.Services.Database.Asset", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorAbsence", b =>
                {
                    b.HasOne("MyDent.Services.Database.Doctor", "Doctor")
                        .WithMany("Absences")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorSpecialty", b =>
                {
                    b.HasOne("MyDent.Services.Database.Doctor", "Doctor")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.ServiceCategory", "ServiceCategory")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("MyDent.Services.Database.DoctorWorkingHours", b =>
                {
                    b.HasOne("MyDent.Services.Database.Doctor", "Doctor")
                        .WithMany("WorkingHours")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MyDent.Services.Database.News", b =>
                {
                    b.HasOne("MyDent.Services.Database.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.Asset", "Image")
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyDent.Services.Database.Notification", b =>
                {
                    b.HasOne("MyDent.Services.Database.Appointment", "Appointment")
                        .WithMany("Notifications")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyDent.Services.Database.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyDent.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ServiceCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDent.Services.Database.Payment", b =>
                {
                    b.HasOne("MyDent.Services.Database.Appointment", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("MyDent.Services.Database.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MyDent.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("MyDent.Services.Database.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDent.Services.Database.Review", b =>
                {
                    b.HasOne("MyDent.Services.Database.Appointment", "Appointment")
                        .WithOne("Review")
                        .HasForeignKey("MyDent.Services.Database.Review", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MyDent.Services.Database.User", b =>
                {
                    b.HasOne("MyDent.Services.Database.Asset", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImageAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("MyDent.Services.Database.UserRole", b =>
                {
                    b.HasOne("MyDent.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDent.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDent.Services.Database.Appointment", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Payment");

                    b.Navigation("Review");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("MyDent.Services.Database.DentalService", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MyDent.Services.Database.Doctor", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Appointments");

                    b.Navigation("DoctorSpecialties");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("MyDent.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MyDent.Services.Database.ServiceCategory", b =>
                {
                    b.Navigation("DentalServices");

                    b.Navigation("DoctorSpecialties");
                });

            modelBuilder.Entity("MyDent.Services.Database.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
